//Text, of which there is a lot.

const essayTexts = [
    {
        id: 0,
        title: "Takealot analysis essay",
        date: "2 May 2023",
        subject: "Interactive Media",
        thumbnail: "images/Thumbnails/TakealotThumg.png",
        thumbnailAlt: "A picture of the Takealot homepage",
        previewparagraph: "In this essay I will be examining Takealot.com, first from a purely technical aspect before then moving onto a brief look into the way that online shops psychologically manipulate customers, with a bit of discussion about the ethics of those tactics.",
        text: `<p>In this essay I will be examining Takealot.com, first from a purely technical aspect before then moving onto a brief look into the way that online shops psychologically manipulate customers, with a bit of discussion about the ethics of those tactics.</p><p>
        First off, I want to start by explaining why I chose Takealot.com. The first reason is because they are one of very few digital companies in South Africa that have a decent market share over their field, rather than playing second fiddle to a foreign company. Because while Meta and Google dominate our online lives, Amazon has found it remarkably difficult to expand their ecommerce business here despite offering digital services since 2004, leaving space for a homegrown market to pop up in the interim (Businesstech, 2023). So Takealot is one of a few competitive South African internet businesses, that’s one reason for choosing them. My other is reason is that they are just, in a way, boring. Takealot have been operating in some way or another since 2002, back when they were still Take2 (Techcentral, 2011), and to my knowledge there have never really been any major scandals with them. They just operate, going about their business in a way that is quietly effective and -importantly for this essay- means that I won’t have any prior biases going into writing about them. This allows for a more objective analysis of the site and improved learning from it, since this essay will look at what’s there, rather than what I am looking for to point out.</p><p>
        Now, starting with the technical side of the site and the homepage, it’s decent. The site doesn’t really follow any kind of strict layout, which could possibly make it harder to navigate for someone who’s not entirely familiar with the internet. One major point the website has in its favour is that it is nicely responsive, adapting well to being resized and zoomed in on. This is important on two levels: firstly, it means those with poor vision can easily resize the site to properly see what is on the page. Secondly, it means that the page is usable on mobile. This is arguably a far bigger deal in South Africa, where 91% of users have mobile devices while just 52% have some kind of computer (TheMedia, 2020). Because of this, any website that is not mobile friendly in South Africa is potentially losing out on around half of it’s market share, which is a massive and obvious motivator for responsive web design. The code of the page itself is decent, featuring aspects of semantic markup that would make it easy for web crawlers to categorize the page, and would also likely be enough for accessibility tools to make use of. So, overall, much like the company itself, Takealot.com’s homepage is perfectly serviceable.</p><p>
        Moving onto an individual product page, I’ll be using the page of the Samsung Galaxy A14 as my reference. Immediately, I’ll acknowledge that this is not perfectly representative of the average experience since Samsung would have provided Takealot with the marketing package for this product. The page even has a disclaimer noting this, which is a nice touch since most companies wouldn’t point that out. The ethics of this practice are a little grey, since they provide larger companies with more money for marketing an edge due to the improved shopping experience. This potentially means that a superior product with less marketing could be overlooked by the customer. Ultimately, marketing as a practice is an area of moral grey, which will be moved on from now because Takealot as a company do not do the bulk of marketing for products themselves as a retailer rather than a manufacturer. Going onto the layout of the page, it’s alright. There is more visual information here than on the homepage, mainly thanks to the marketing package provided by Samsung since Takealot themselves usually only provide a boring text box, and all the relevant information is immediately accessible. There are also simple options for purchasing, along with several links to other parts of the site that make it easy to find further information about the service. All of this is par for the course, but also incredibly vital since any obstacle in the way of making a purchase could lead to a potential loss of a customer. The biggest problem I have with this product page is that it really lacks semantic markup, being a mess of <div>s that would make the page a nightmare for anyone relying on accessibility technology to navigate. Doubly so because so much of the information on this page is visual. But overall, much like the home page, this page is perfectly passable without doing too much over the necessary amount.</p><p>
        The reason why this website is so utilitarian is likely due to the risk of it becoming flashy, or even worse, tacky. Online shops operate heavily on trust since they offer a highly complex physical service in exchange for digital transactions of very real wealth. And when it comes to the trust users have in a website, the three most important factors are ease of use, design (including professionalism) and transparency (Tasin, 2017: 47). Going through these in order, the first was clearly the biggest focus for Takealot. The website is easy to navigate, with information being limited to just enough for users to know what they’re looking for without ever feeling overwhelmed. Things just sort of work, and for a site that is as focused on providing a service as Takealot is, I think it is perfectly acceptable.</p><p>
        Moving onto design, this is an area where the site is somewhat lacking. Just compare the page for the A14 on Takealot to Samsung’s own website (Samsung, 2023) and the difference becomes clear. Samsung provide a far more dynamic, interactive page that immerses the user in the experience of owning the phone. Of course, the reason for this greater focus on design is twofold and understandable. Firstly, Samsung has vested interest, since they are the manufacturer of the product rather than a pure retailer like Takealot is, not to mention Takealot simply does not have the resources to provide an outstanding product page for every single item they sell. The second reason is the more important one, and that is the risk involved with trying to push the design. The line between pleasing and tacky is a thin one, and one that online shops cannot risk crossing since losing professionalism would mean losing trust (Tasin, 2017). So, generally, these sites simply reel in their design to minimize the potential risk of seeming unprofessional that they take on, at the cost of some aesthetic quality when compared to less function first sites.</p><p>
        Finally, the last quality that determines trust is transparency. Starting with the good, Takealot are generally clear with information about the service, like order statuses, seller information and the large amount of information about the actual company they provide at the bottom of the page. This is vitally important since nobody is going to trust their personal information and -more importantly- money to a company that is hard to track down information about. However, where I have an issue is in how Takealot displays its pricing. Now it’s not as bad as amazon obscuring their prices behind different retailers and second hand items, making it far harder to find the actual price of an item (although it is worth noting that Takealot have introduced a similar system of showing different suppliers) but it’s still hard to figure out exactly how much an item usually is and if it is on sale in some kind of way because Takealot frequently displays items that are below typical retail price on their service the same way as the do items that are on sale. They also don’t explain the exact details of sales, making it very hard to shop around said sales and pressuring users into making a purchase they otherwise wouldn’t. This is a common tactic of online retailers, obscuring the prices of items, because it is proven beyond all doubt to be effective. During their annual “Double Eleven” sale, Alibaba reports massive profits year after year, with a staggering 84 billion USD of GMV being moved in eleven days during the 2021 sale (Li et al. 2022). That is a value equivalent to around a quarter of South Africa’s national GDP (Trading Economics, 2021), being moved in eleven days, by one company. So it is only natural that other companies follow in the footsteps of that behaviour. But this essay is not about making money, it’s about the ethics of UX, and the banners and prompts, along with the more subtle techniques used by companies to reduce users’ rationality (Li et al. 2022) certainly do not pass the bar of ethical. No, these are psychological tactics used purely to force people into spending money that they wouldn’t have otherwise and may even possibly not have available to spend. This profit first mentality affects lives and can have serious consequences. At the very least, it does seem that users are becoming slightly more aware of these tactics. Tools like SteamDB’s past price comparison tool are also extremely useful for neutralizing these psychological strongarm tactics, but it doesn’t really change the fact that they shouldn’t be utilized at all. At least not in a perfect world.</p><p>
        In conclusion, looking at Takealot was nice. Its utilitarian nature feels so earnest and quaint after the psychological warfare that is opening Amazon or Instagram. I know that the expectation for this essay was probably to find a website that strangles kittens and to tear it apart, but I think that we need to look at “just fine” as much as we need to look at the worst of the worst. These are the websites we’ll likely spend most of our time making after all, and Takealot just so happens to be a good, homegrown example of that. So good on you Takealot. You’re fighting the good fight for South Africa, and that’s a lot more than can be said for most of the products we use.</p><p>
        References:</p><p>
        Pages Used:</p><p>
        Takealot Homepage: https://www.takealot.com/</p><p>
        Samsung Galaxy A14 store page: https://www.takealot.com/samsung-galaxy-a14-64gb-lte-dual-sim-black/PLID92717012</p><p>
        Sources:</p><p>
        Businesstech. 2023. Takealot says it’s ready for Amazon. Online. https://businesstech.co.za/news/internet/680637/takealot-says-its-ready-for-amazon/. 02/5/2023.</p><p>
        Li, T. Li, W. Zhao, Y. 2022. Rationality manipulation during consumer decision-making process: an analysis of Alibaba’s online shopping carnival. Electronic Commerce Research, Vol. 23, pp. 331-364.</p><p>
        Samsung. 2023. Galaxy A14 5G. Online. https://www.samsung.com/africa_en/smartphones/galaxy-a/galaxy-a14-5g-black-64gb-sm-a146pzkdafa/. 02/5/2023.</p><p>
        SteamDB. 2023. Sales. Online. https://steamdb.info/sales/. 02/5/2023.</p><p>
        Tasin, N. B. 2017. Factors Influecing Customer's Trust in Online Shopping Among Executives in a Bank. Malaysian Journal of Social Sciences and Humanities, Vol. 2, No. 3 (November 2017), pp. 46-59.</p><p>
        Techcentral. 2011. Take2 rebrands, shoots for R1bn in sales. Online. https://techcentral.co.za/take2-rebrands-shoots-for-r1bn-in-sales/184072/. 02/5/2023.</p><p>
        The Media Online. 2020. Device penetration rises in South Africa as digital becomes the new normal. Online. https://themediaonline.co.za/2020/11/device-penetration-rises-in-south-africa-as-digital-becomes-the-new-normal/. 02/5/2023.</p><p>
        Trading Economics. 2021. South Africa GDP. Online. https://tradingeconomics.com/south-africa/gdp. 02/5/2023. </p><p>
        `
    },{
        id: 1,
        title: "Ontology and Games Essay",
        date: "24 April 2023",
        subject: "Digital Art Theory",
        thumbnail: "images/Thumbnails/Snake.png",
        thumbnailAlt: "A picture Naked Snake",
        previewparagraph: "In this essay I will be examining Takealot.com, first from a purely technical aspect before then moving onto a brief look into the way that online shops psychologically manipulate customers, with a bit of discussion about the ethics of those tactics.",
        text: `<p>Introduction:</p><p>
        In this essay I will be discussing the work of Noel Carroll (1997) as it relates to video games, using an essay by Grant Tavinor (2011) as a starting point. Once I have discussed video games as mass art, I will then discuss the Type/Token relationship (Hilpinen, 2012) as it relates to video games as a genre, before finally concluding with a discussion about why using both methods of analysis can be useful when talking about games. Throughout this essay, I will also be referencing Metal Gear Solid 3 (2004), since it serves as a good case study through which these topics can be discussed.</p><p>
        As Mass Art:</p><p>
        To start with the idea of Mass Art, the concept refers to the idea that -thanks to technology- it is now possible for many identical or near identical copies of one artifact to be made (Carroll 1997). When Noel Carroll made this definition in 1997, he also clarified that mass art must be accessible (so not Avant-Garde) and must provide the same experience to anyone who consumes it (ignoring context of how it was consumed) since if it provides a unique experience to each person than that is not mass art but rather a cultural phenomenon (Carroll, 1997). This definition works well for the nineties, but one thing that Carroll failed to consider is video games, likely since they were in their nascence at the time. Since video games have an interactive element, that means that each person’s experience with them will differ by some degree. However, I would like to argue that video games are still mass art, just on a technical level.</p><p>
        To take the example of Metal Gear Solid 3 (2004), every copy of the game will be the same technical product on the disk. Every copy will use the same code base, assets, cutscenes and dialogue. While the player’s experience will somewhat differ based on their choices, the fundamental technical product underneath everything is still the same. In this way, as a technical product, games can be considered mass produced artistic products.</p><p>
        To further clarify the ways in which video games are mass art, it is worth analysing the other specific requirements that Carroll (1997: 190) provides for being classified mass art. Firstly, Carroll does specify that mass art must come from a medium that is considered “art”. The debate of video games as art is still an ongoing one, but in the day and age in which even mainstream games made by large studios can exhibit stunning art direction (see Ghost of Tsushima (2020), it is certainly valid enough to say that they are for this discussion. Carroll also states that mass art must be easily producible in bulk, a specification he inherited from the work of Walter Benjamin (1936), which is a requirement that video games certainly meet. The Metal Gear series alone has sold over 58 million copies (Metal Gear Informer 2022), which is certainly enough to consider it massively produced. Carroll also adds onto Benjamin, stating that mass art must be able to be experienced in multiple places simultaneously. Since each copy of Metal Gear Solid 3 can be enjoyed asynchronously separately on local systems, it also fulfils this criterion. Finally, for something to be Mass Art, it must be accessible. This is an extension of the idea that for something to be Mass Art it cannot be Avant-Garde and is an area where video games stumble a bit. Fortunately, the case study of this essay is still able to qualify as Mass Art with this requirement because of two reasons. Firstly, Carroll does give leeway to allow audiences to have some basic context of the artwork beforehand (as pointed out by Tavinor (2011)). Secondly, Metal Gear Solid 3 (2004) and many other games do feature easy modes, reducing the barrier for entry and exclusivity without diluting the interactive nature of the game to much.</p><p>
        However, the definition of Mass Art is still quite constricting for video games. It reduces them down to their technical fundamentals which, while still impressive and important, drastically diminishes the role of the most important part of video games as a medium: interactivity.</p><p>
        As Types and Tokens:</p><p>
        By integrating the idea of types and tokens into the discussion, one can have a far more nuanced conversation about how video games exist as mass art, but also as individual experiences that are created by the interaction between the player and game systems.</p><p>
        To start off with, what are types and tokens? Charles S. Pierce defines them as such: “Such a definitely significant Form, I propose to term a Type. A Single event which happens once and whose identity is limited to that one happening … I will venture to call a Token.” (Hilpinen, 2012) In other words, a Type is a concept that can be utilized in several contexts, while a token is a single occurrence of that type. The example given by Tavinor (2011) revolves around Star Wars. Any individual screening of A New Hope (1977) is going to be the token, while any movie in which Luke Skywalker blows up the Death Star is the type. </p><p>
        Metal Gear Solid 3 (2004) is a good example of this relationship on a technical level. The game has four separate versions -Snake Eater, Subsistence, HD and 3D- which each represent a different token, however they are all still of the same type. In this essay I’ve been speaking about Snake Eater specifically, but you could very easily change the essay to be about any of the other versions as well.</p><p>
        What makes video games unique in a type/token relationship is that they are an interactive medium. Because of this, the variations between two people’s playthroughs -each of which could be considered a token- can vary drastically. This is doubly true for a game with sandbox elements such as Metal Gear Solid 3 (2004). Because every playthrough is undoubtedly of the same type, since the fundamental plot of the game always plays out the same regardless of players, but certain events may change drastically based on the players actions.</p><p>
        Taking The End’s excellent boss fight as an example, players can choose to engage it in any number of ways. As a tense sniper duel, as a battle between a young warrior -guns blazing- and an old man trying to outsmart him, as a battle of attrition as Snake tries to non-lethally neutralize him, and many more. This is not even to mention the two ways the boss fight can be avoided, either by killing the End when he first appears or by waiting for him to pass away naturally of old age. All of these alter the token that is the player’s individual playthrough, without affecting the overall type that much. </p><p>
        However, the most fascinating effects come into play when looking at Metal Gear Solid 3’s (2004) non-lethal options. Choosing whether to kill each enemy the player comes across is entirely up to them and doesn’t affect the story on any mechanical level. However, it does affect the semiotics of the game. Although it was technically the player who pulled the trigger, the immersive quality of games means that the player should on some level associate their actions with their characterization of Naked Snake. Because of this, his perceived characterization will change from player to player based on their actions, creating vast semiotic differences between each token and player’s experience.</p><p>
        The Ontology of games:</p><p>
        Video Games are very interesting to talk about ontologically, because ontology is a branch of philosophy that seeks the explanation and classification of entities (University of Warwick, 2017). The reason why the relationship is so interesting is because it’s so hard to talk about. Video Games (just video games, not even games generally) are very ontologically fluid. They borrow from various mediums, from films to literature, and in doing so create an experience that is very difficult to quantify as one specific thing. Taking just Metal Gear Solid 3 (2004) as an example, it’s an interactive experience, but it also takes heavy ques from the medium of film for its cutscenes, and even some inspiration from literature for its dialogue heavy Codec calls. So, in this one game alone, it is common to encounter inspirations from at least three different mediums.</p><p>
        In short, the reason why video games feel so personal despite being mass art is because of the signifiers the player injects into their own token through their interactions. Each copy of a game may be near technically identical, but the player maps their own meaning onto the token through their actions, creating new signifiers that weren’t there before and then reinterpreting them as the audience into entirely new sign. This creates new depth to the artifact that wasn’t there before, but only for the people who experience that playthrough and interpret the new signs. </p><p>
        In conclusion, the reason why I chose to analyse the game from these two separate perspectives is to create discussion. To create a comprehensive framework for video game analysis, one needs to take ques from many fields of thought and theory. That is what Tavinor (2011) did, and that is also what inspired me to do the same here. This essay is by no means that framework for comprehensive analysis, but instead its purpose is to bring up two schools of thought that should be used more often when discussing video games, because they allow and begin a discussion about of one of the most unique qualities of the medium. That being the fact that they are both a personal experience and a piece of mass-produced media.</p><p>
        References:</p><p>
        Benjamin, W. 1936. The Work of Art in the Age of Mechanical Reproduction.</p><p>
        Carroll, N. 1997. The Ontology of Mass Art. Spring, Vol. 55, No. 2, Perspectives on the Arts and Technology (Spring, 1997), pp. 187-199.</p><p>
        Ghost of Tsushima, 2020. Play Station® 4. Washington: Sucker Punch.</p><p>
        Hilpinen, R. 2012. 2012 Presidential Address: Types and Tokens: On the Identity and Meaning of Names and Other Words. Transactions of the Charles S. Peirce Society, Vol. 48, No. 3 (Spring 2012), pp. 259-284</p><p>
        Metal Gear Solid 3: Snake Eater, 2004. Play Station® 2. Tokyo: Japan.</p><p>
        Metal Gear Informer. 2022. Metal Gear series reaches 58.3 million copies sold. Online. https://www.metalgearinformer.com/?p=38857. 24/4/2023.</p><p>
        Star Wars: Episode IV - A New Hope, 1977. Film. Directed by G. Lucas. America: 20th Century Fox.</p><p>
        Tavinor, G. 2011. Video Games as Mass Art. Contemporary Aesthetics, Vol. 9, No. 9.</p><p>
        University of Warwick. 2017. Ontology. Online. https://warwick.ac.uk/fac/soc/ces/research/current/socialtheory/maps/ology/. 24/4/2023.  </p>  
        `
    }
]


const blogTexts = [
    {
        id: 0,
        title: "Week 1",
        text: `<p>I first set up my Github account in grade 10. My computer science teacher was really cool, and worked for Google on AI technology back before everyone was doing it. It was an awesome time, but going back to that account now was surreal because I forgot how dumb I was back in that time. I've changed the childish username and the old profile picture now, but I've never felt more disappointment in myself than when I saw I had a Donald Trump Pepe profile picture. My politics even at the time didn't reflect that image (not that a fifteen year old knows anything about politics), but still it's interesting to see that I didn't yet have the media literacy to understand that I was going around with what is basically one step away from just putting up a swastika as my profile picture. Besides that, I'm also still on a repository with my old classmate Arnold, which was a funny reminder that he exists. I hope he's doing well. Anyways, I've re-set up the Git account to better reflect who I am now and so that I can use it in a slightly more academic setting.</p><p>
        Aside from my Git experience, I also did a lot of the readings last week. As someone with a passion for computer science, I've absolutely loved looking at these readings. I had a morning where I had to wait for a long while with nothing but Ulwazi to keep me entertained, so I've read the Bush, Turing, Englebart and Nelson.</p><p>
        The most fascinating insight I got out of the readings was with Nelson's "Proposal for a Universal Publishing System and Archive". Not so much because of the reading itself, but because of a modern parallel that I think is worth bringing up for discussion. In Nelson's reading, he proposes a vision of an idea that would one day go on to change the world, but because of the restrictions he places on it and the possessive control he wanted placed over the idea, his vision never came to pass. That reminds me of something else in the modern day: Facebook's metaverse. Much like Nelson's Xanadu, Facebook's idea for an immersive VR social space does have the potential to enrich society. A place where people can be anyone, go anywhere and learn anything as if they were practically there does sound great, but Facebook's vision is flawed because they're trying to build it as a system that they solely run and profit from, as opposed to a democratized system in which anyone can carve out a slice that is truly their own. And much like Nelson's system, I believe Facebook's plan is destined for failure, doomed to be replaced by a system that puts power into the hands of the individuals instead of accumulating it under the control of a single dystopian company that controls information on a far greater scale than any other power on earth.</p><p>
        I also think whatever that platform is will launch with the capacity for users to have legs.</p>`,
        preview: "I first set up my Github account in grade 10. My computer science teacher was really cool, and worked for Google on AI technology back before everyone was doing it. It was an awesome time, but going back to that account now was surreal because I forgot how dumb I was back in that time. I've changed the childish username and the old profile picture now, but I've never felt more disappointment in myself than when I saw I had a Donald Trump Pepe profile picture. My politics even at the time didn't reflect that image (not that a fifteen year old knows anything about politics), but still it's interesting to see that I didn't yet have the media literacy to understand that I was going around with what is basically one step away from just putting up a swastika as my profile picture. Besides that, I'm also still on a repository with my old classmate Arnold, which was a funny reminder that he exists. I hope he's doing well. Anyways, I've re-set up the Git account to better reflect who I am now and so that I can use it in a slightly more academic setting.</p><p>",
        color: "greenback"
    },{
        id: 1,
        title: "Week 2",
        text: `<p>My main focus this week was on the website itself, since I did a lot of readings last week. I got started, and built a small prototype using some resources I found online to give me a bit of guidance, but to be honest, it was disorientating.</p><p>

        Because of the protests, I missed the Wednesday class last week, and even though I know that Wednesday is largely theoretical, it still felt like I had missed something important. But I didn't let that slow me down too much in the end, and so I got to work trying to build a basic prototype. That process really had me feeling what someone -Kieran, I think- said about how scary it is to do something with no direction. All the endless possibilities stretched out before me, and I had to decide what to do with them.</p><p>
        
        Ultimately, the web prototype I built was mainly built around the "The Missile Knows Where It Is, Because It Knows Where It Isn't" meme. It's stupid, I know, but I find it a lot easier to work when I latch onto something funny to put at the center of my work. It gives me a guideline, and that's really all I need a lot of the time. Of course, there is a major downside, and that is how I'll have to restart the page mostly from scratch once I eventually start getting it ready for a proper version I can submit. However, I don't think that's the end of the world, and I'm sure that the original page will live on as an easter egg in the site somewhere.</p><p>
        
        Besides getting started with my website, I also took a look at the HTML readings, namely the first two Bruce Lawson readings. They were a little hard to follow since HTML is so new to me (I've only ever dabbled into it lightly once before) but I think that they serve as nice resources, and it will be nice to know they exist so I can go back in future. </p>`,
        preview: "My main focus this week was on the website itself, since I did a lot of readings last week. I got started, and built a small prototype using some resources I found online to give me a bit of guidance, but to be honest, it was disorientating.",
        color: "coralback"
    },{
        id: 2,
        title: "Week 3",
        text: `<p>This week’s blog post is going to be a memory test, since I managed to somehow lose my original blog for week three and now I have to rewrite it in order to include it with my final website.</p><p>
        Firstly, the reading. I think that Mailloux was a fun reading with universal application. Convention isn’t just a web design thing, it happens everywhere, and this reading shows how we can look at the applications in other fields to then reapply to our own work. It also compliments the “Bad doors are everywhere” video really well, with the reading serving as a more theoretical supplement to the fun informal video.</p><p>
        Otherwise, it’s crazy to look how far my site has gotten since week 3. When I did the first version of the blog, the site was little more than a dream. Now the site is nearly done, with just a few final touches required. It’s insane to see how much so little polish can do to take your site from something disgusting (see week 3 exercise for an example of that) to something that looks less than professional, but still appealing and could with a bit more work become something truly impressive.
        </p>`,
        preview: "This week’s blog post is going to be a memory test, since I managed to somehow lose my original blog for week three and now I have to rewrite it in order to include it with my final website.",
        color: "flamingoback"
    },{
        id: 3,
        title: "Week 4",
        text: `</p>Convention is a funny thing. I mean, where did the way we start our blogposts come from? We all use the same format, yet it was never prescribed to us. We didn't get it from a reading, or from any kind of brief, someone just started using it and we all started following it.</p><p>

        Whenever discussions of convention come up for me, I can't help but think of the "first napkin" speech from Jojo's bizarre adventure. It's a lot of rambling in a typical anime villain nonsense speech, but what does stick with me is the idea that the person who determines convention is the first person who has the will to act. In other words, the person who "takes the first napkin" at a table is the one who determines which napkin belongs to who. And you can see that principle at play in a lot of places. Why do we put most of our navigation menus on top of the web page? Why do we drive on the left or right side of the road? Why do we read left to right, top to bottom, especially when some cultures read right to left instead? Simply, a lot of it just comes down to whoever had the chance to decide on the convention.</p><p>
        
        That said, not every convention is just because someone started doing it and everyone else did the same. Take the "There are bad Doors everywhere" reading, for example. There are "correct", intuitive ways to make doors work, and that goes for a lot of other things as well. A button with an arrow pointing up should not take you to the bottom of the page, and at this point we are probably settled enough with the idea of the "X" button closing programs that it shouldn't be changed to make them full screen.</p><p>
        
        So I guess what I'm getting at is that convention is a funny thing. It's weird and fluid, but at the same time strangely fixed. Sometimes it comes from someone taking that first napkin, that big leap, and other times it comes from somewhere deep in the human psyche. Some deep fixed understanding that a door with a handle is a pull door, or some such like that. Convention is a complex beast, and it's our job to wrangle it.</p>`,
        preview: "Convention is a funny thing. I mean, where did the way we start our blogposts come from? We all use the same format, yet it was never prescribed to us. We didn't get it from a reading, or from any kind of brief, someone just started using it and we all started following it.",
        color: "blueback"
    },{
        id: 4,
        title: "Week 5",
        text: `We haven’t had a prompt for this week, so I’m kind of flying blind here. Forgive me if this is a bit rough.</p><p>
        This week has marked the official start on my website. I figured it was about time to actually get something down in code, because I learnt the hard way in recent Game Design assignment how much a single code mess up can keep you busy. Seriously, I ended up spending eight hours on that game and of that about three were trying to finish one system, which didn’t even get fixed fully. So that sucked, but I’m learning from it and I’m starting this assignment nice and early. A page a day is my current goal, and at this rate I’ll easily be done with everything with time to spare for fixing any screw ups and making the whole thing look even better wherever possible.</p><p>
        This is where I would talk about the readings, but those have all been pushed up to next week so instead I want to talk about this flu, and covid trauma. It’s crazy, right? For me as someone who really did not cope over covid (it came right as I was finally ready to stop being inside so much, so not good at all) I get deeply afraid the moment a lot of people start getting sick. I know I probably shouldn’t, since I doubt anyone is willing to repeat the sheer economic sledgehammer that was lockdown over some slightly more intense flu strain, but Covid affected us all in weird ways and for me it’s made me scared of having to spend time at home against my will, because I feel like everything that happened to me in the past four years is starting all over again. </p><p>
        Weird tangent, I know, but it’s what’s on my mind at the moment, and honestly what else is this blog for if not intelligently discussing what I’m currently thinking about.
        </p>`,
        preview: "We haven’t had a prompt for this week, so I’m kind of flying blind here. Forgive me if this is a bit rough.",
        color: "greenback"
    },{
        id: 5,
        title: "Week 6",
        text: `</p>I am so tired today. And I shouldn’t be, I mean I’ve had all of Sunday to relax and we’re winding down after a short, easy first block for the second block now (if I’m not mistaken) so I really shouldn’t be this tired. And yet I am. I’m so tired that I would rather talk about being tired than getting started on my website this week, because I think it’s interesting that I am tired.</p><p>
        I think it all comes down to Covid, as it always does. During Covid, and even before in my case, I got used to only really doing something of note maybe two, three days a week? And it was violently depressing, don’t get me wrong. I think my mental state has been a lot better not that I’m actually going out into the world and interacting with things, but I’m also a lot more tired, and I think it’s because I don’t have two to three days to recover from every social interaction anymore (except for when I do) and so my body is taking a long time to adjust. There’s almost certainly an extrovert aspect to it as well. I personally fall into the category of people who love socializing and spending time with people, but I’m also drained by it. It doesn’t relax me at all, unless it’s online. So now that I’m always finding chances to interact with people, I’ve been a lot more tired. It’s weird and funny, but yeah. I guess the last thing I’ll add is that I’m very much looking forward to the big social event on wednesday. It’s going to be so nice to finally see everyone in one place, I can’t wait.
        <p>`,
        preview: "I am so tired today. And I shouldn’t be, I mean I’ve had all of Sunday to relax and we’re winding down after a short, easy first block for the second block now (if I’m not mistaken) so I really shouldn’t be this tired. And yet I am. I’m so tired that I would rather talk about being tired than getting started on my website this week, because I think it’s interesting that I am tired.",
        color: "flamingoback"
    },{
        id: 6,
        title: "Week 7",
        text: `</p>So the funny thing about this blog post is that as soon as I'm done writing it, it'll go up on my website. Yes, my website is coming along! I've finally gotten over that first big hurdle when you learn a new skill when it comes to webdev, so now I'm good enough I can do things but not so good I expect to do them well. So everything is fun and exciting and I'm just having a ball putting together everything for my site. It is excellent. Just touch wood it stays that way.</p><p>
        Now then, for the quick IxD checkup on how I'm doing:</p><p>
        Goal Alignment: Not a deep topic right now. All I need is a site that's easy to navigate at the moment, all the manipulation and mind games will come later.</p><p>
        Information structure: This one has been a big deal. I've been putting a big emphasis on making sure things aren't cluttered, with the goal of keeping the site easy to navigate. It's hard work, especially with how much CSS is involved, but it's better to keep on top of it as you go -I think- so that you don't need to go back sort through the mess you made after you forgot your plans for it.</p><p>
        User flow: This is something I'm keeping in consideration, so far, but one I could probably try map a little more. The main thing I'm doing towards this end is keeping a top bar with all the main pages accessible at all times, which should make the site relatively easy and consistent to maintain. It does follow the three click rule so far, which is a major win.</p><p>
        Interface elements: This has been a more organic area. I started by just putting down whatever, but as the site has gone along, I've improved the weak areas and started to form a convention in others. I don't think you always need to stick to "best practice" dogmatically, but any time you do deviate from it then it's important to stay consistent in that deviation.</p><p>
        Design: My design documents are taking shape as I learn, but when they're done I'll put them in the Design section of my site, and update anything that's below the standards they set.</p><p>
        Implementation: My website has largely been simple so far, but I'm also trying to do a lot with that little. That means striking visuals and complete functionality wherever possible, so that I can represent a more complete design.</p><p>
        Reading: This weeks reading is essentially an exercise in quantifying experiential information. That's why it doesn't speak to me. I personally prefer to keep my sciences in science and my art in art, teasing out experiential information and working based on feel, rather than data. That's not to say there's no place for data in art, especially in web design, which blends the lines of science and art so much, but I prefer to use that data to improve what I design through feel, rather than creating sterile feeling products by designing using data. Again, just personal preference, but I'm trying to be the change I want to see in the world.
        </p>`,
        preview: "So the funny thing about this blog post is that as soon as I'm done writing it, it'll go up on my website. Yes, my website is coming along! I've finally gotten over that first big hurdle when you learn a new skill when it comes to webdev, so now I'm good enough I can do things but not so good I expect to do them well. So everything is fun and exciting and I'm just having a ball putting together everything for my site. It is excellent. Just touch wood it stays that way.",
        color: "blueback"
    },{
        id: 7,
        title: "Original Conclusion",
        text: `</p>So then, with everything done, I think it’s about time to reflect on what I’ve accomplished. Well, much like everything on this site, it’s a lot and a little. On the one hand, the site is certainly a long way from its humble beginnings. On the other hand, I’ve learnt a lot over the course of making this assignment, which means that my skill level is just high enough to know how little I’ve actually mastered. As Andre said that one time, web design is something you can very easily dedicate your whole life to. So, I’ve only just begun the long road. Anyways, in the name of just getting a bit of self evaluation out here in order to begin the process of learning from this assignment, I want to discuss what I think are the best, worse and most underwhelming pages on this site. Starting with…</p><p>
        THE WORST: Obviously it’s gotta be the Exercise 3 page. It’s so crowded and ugly, and while I do think that there’s a way to do a dense web page, this is not it. The colors also just don’t mesh at all, and in general the whole this is just horrifying to look at. 0/10, not impressed with myself at all. Then again, this page was literally how I learnt CSS, and it also came long before I had a unified style for the site. So there’s most certainly a reason why it’s aged so poorly.</p><p>          
        THE MOST UNDERWHELMING: Probably going to have to be the home screen for me. I had an idea for this, and while I was kind of able to get something happening with my limited skill, it’s still far away from where it could possibly one day be. Things like animations and Javascript would go a long way, but I think the biggest problem I have with it right now is that annoying white bar I just can’t seem to fix.</p><p>
        THE BEST: I think my favorite page on the site might actually be the profile. That’s surprising, because I was dreading doing a profile. Now the actual section that’s just about me does suck, of course, because I really don’t like writing about myself. But the section that focuses on music is probably my favorite part of the site. It’s so visually appealing, and the functionality of being able to click on the album arts to see the album is probably the element of the site I’m most proud of. It should also come as no surprise that it was the last part of the site I finished before submitting.                
        <p>`,
        preview: "So then, with everything done, I think it’s about time to reflect on what I’ve accomplished. Well, much like everything on this site, it’s a lot and a little. On the one hand, the site is certainly a long way from its humble beginnings. On the other hand, I’ve learnt a lot over the course of making this assignment, which means that my skill level is just high enough to know how little I’ve actually mastered. As Andre said that one time, web design is something you can very easily dedicate your whole life to. So, I’ve only just begun the long road. Anyways, in the name of just getting a bit of self evaluation out here in order to begin the process of learning from this assignment, I want to discuss what I think are the best, worse and most underwhelming pages on this site. Starting with…",
        color: "flamingoback"
    },{
        id: 8,
        title: "Week 8",
        text: `<p>I am not happy with my assignment 1 website.</p><p>

        I saw it coming before I submitted, and I don't really have an excuse. I realized as I was finalizing my website that it just was not good enough. I did not put in enough effort, at all, anywhere. To be honest, I will probably start from scratch for the next assignment, because this website that I've made, while it has its charm, is just not a good starting point. My refusal to go back and refine really came back to bite me in this assignment, but moaning and complaining isn't going to do anything, so for now I just need to treat this as a learning experience and put in the effort next time.</p><p>
        
        As for the readings, I think that the Graham reading puts data into perspective really well. What I mean by that is usually when we talk about the internet, we just say "US domain names have a disproportionate presence" and move on, but here these visuals really allow the information to be displayed in a way that the human brain usually isn't able to because we're limited in the scale that we can see things in due to our finite perception.</p><p>
        
        The other reading, the Ballatore one, is also thought provoking, although not in the same visual way. I probably could have told you that local businesses are discriminated against by search engines, but it's mind boggling to see just how much. That said, as Hanli pointed out in the lecture, the way of generating data here is limited. My main issue with it is that it ignores the impact that web profiling actually has on the results a user sees. My experience will be somewhat homogenized, no matter where I am in the world, because Google "knows me" in a way because of the sheer amount of data it gathers on me. And let me put it in no uncertain terms: That is a bad thing. What it leads to is me being surrounded in an echo chamber, where my biases and opinions are reinforced because I am not given unfiltered access to the internet. This is especially dangerous because I am a white male, so the algorithm says that statistically my echo chamber should be one filled with hate. One of my scariest realizations of the last few years is how close I was to going down the "anti-woke" pipeline in my teenage years, with the power of more self awareness as I got older helping me to realize how my seemingly innocent gaming content on Youtube was being co-opted in order to brainwash me into a hateful person. The pipeline is terrifying, and I'm eternally grateful I was lucky enough to avoid falling down it.<p>`,
        preview: "I am not happy with my assignment 1 website.",
        color: "greenback"
    },{
        id: 9,
        title: "Week 9",
        text: `<p>Website Development:</p><p>

        I have not been working on my website. I know, I really should be, but I have other subjects and a lot of assignments to do for those. More importantly though, I am trying to decide on a new direction for my site. Because clearly the last one was flawed beyond comprehension, so I need to start over and build on better foundations so that I don't repeat the same mistakes a second time. At least that's what it looks like from where I'm sitting. At least when I do restart, soon, I will be able to do so from a more solid foundation of knowledge gained from all the lectures with Andre on Java.</p><p>
        
        Reading:</p><p>
        
        I have chosen to read "The Fourth Industrial Revolution – The Case of South Africa" by Ewan Sutherland. This is because it is a rare reading that directly discusses South African political policy, as opposed to discussing our social context or a broader African viewpoint. I will be discussing this reading subheading by subheading.</p><p>
        
        Industrial Revolutions in South Africa: In this section, the past colonial context of Industrial Revolutions are first discussed, before the author gets into a hypothetical discussion of what the effects of the Fourth Industrial Revolution could be for Africa. In particular, the Author Highlights the fundamental inequality present in 4IR discourse, with the risk of exploitation by those in positions of power (particularly dictators) being outlined.</p><p>
        
        Industry Policy in South Africa: This section focuses on the historic failures of Government in SA to deliver any kind of meaningful industrial reform that prodies the jobs and economic stimulus needed to close the massive gap between the poor and the middle class in South Africa. The focus of this discussion is around the automotive industry, which historically has been an excellent way for countries to stimulate their economies, but there is also discussion of the further risks that the 4IR presents, since it would reduce the potential benefits of industrial reform by reducing the number of jobs created and requiring highly skilled workers for the remaining few, which South Africa is lacking in because of its poor education system.</p><p>
        
        Industrial Automation: The Author declares this area a mixed threat. On the one hand, despite fears of humans becoming redundant in a matter of years, the Author cites Arntz et al. saying that the overall losses will only be around 12 percent at most, although poorly qualified workers will bear the brunt of the losses. On the other hand, a great deal of the focus here is about how highly skilled workers will be able to move across to new 4IR industries, with the operative being "highly skilled". The problem is that there is no way for a company to increase their income by jumping straight to services, and since South Africa is still so industrial, a loss of manual labor jobs like the one threatened by the 4IR pundits could be devastating for our employment rates.</p><p>
        
        My Conclusion: The statement "automation removes low skilled work" is one that is very clearly negative for South Africa, but I think it's important to understand just how bad it'd be. We already have a pathetic 39.4% absorption rate (the same as Afghanistan), and the introduction of 4IR policies would only widen that gap. But at the same time, a lot of people don't think that way, saying that the new jobs would be enough. What those people refuse to acknowledge is that those are less jobs for more skilled people, both of which would be devastating for South Africa.<p>`,
        preview: "I have not been working on my website. I know, I really should be, but I have other subjects and a lot of assignments to do for those. More importantly though, I am trying to decide on a new direction for my site. Because clearly the last one was flawed beyond comprehension, so I need to start over and build on better foundations so that I don't repeat the same mistakes a second time. At least that's what it looks like from where I'm sitting. At least when I do restart, soon, I will be able to do so from a more solid foundation of knowledge gained from all the lectures with Andre on Java.",
        color: "coralback"
    },{
        id: 10,
        title: "Week 10",
        text: `<p>I am planning on adding a javascript based top bar to my site. It should unify the experience across all pages and make the whole thing a fair bit easier to develop since I will no longer have to worry about changing things on six pages when I make a minor change on one. I would also like to build a search function at some point, to make it easier for people to scan through my essays and blogs, but that’s a future plan. Otherwise, I have very little to say, because I am in a depressive state at the moment and don’t really have the capacity to expand on my feelings very much at all.
        <p>`,
        preview: "I am planning on adding a javascript based top bar to my site. It should unify the experience across all pages and make the whole thing a fair bit easier to develop since I will no longer have to worry about changing things on six pages when I make a minor change on one. I would also like to build a search function at some point, to make it easier for people to scan through my essays and blogs, but that’s a future plan. Otherwise, I have very little to say, because I am in a depressive state at the moment and don’t really have the capacity to expand on my feelings very much at all.",
        color: "blueback"
    },{
        id: 11,
        title: "Week 11",
        text: `<p>This is probably the most important week in IM for me so far. In short, I am failing right now. At some point soon, I’ll try and ask for a chance to potentially redo assignment 1, or otherwise somehow recover a few marks. If that’s not an option, then it’s done. I’m not spending time or energy on a subject that I cannot possibly pass, and having done the maths, believe me when I say I cannot pass this class with my current average.</p><p>

        It does raise a good question though, which is what should I do if I cannot change my marks. I said a few seconds ago that I’ll give up completely, but that goes entirely against my philosophy as a person. I don’t want to be a person who just gives up on things, perhaps because it is entirely my first reaction a lot of the time. So then what do I do? Scream into the void, hoping that something works? I don’t know, I can’t know. It’s an impossible situation, one that leaves a blight on my academic career either way, one that is really frustrating because I could have probably avoided it if I had just been more willing to work with my peers and had seen what I did wrong sooner. I mean I probably could have avoided this whole situation in a few minutes if I saw that we needed references in our writing section, which is where I’m assuming I went wrong in assignment 1. Yeah, the whole thing just sucks.</p><p>
        
        If there is one big takeaway from all this projecting of anxiety onto the page, it’s that the way we do assignments in this course sucks. Big time. The primary reason I’m in this situation is because of a lack of feedback, caused by how we operate in a complete vacuum with our assignments. If I had of known that my assignment 1 was terrible midway through, or that more was riding on my essay than I could ever have imagined, then I would have been able to adjust my plans accordingly. But because I didn’t know any of this until now, suddenly the fact that we only do three assignments in a semester compounds with the fact that I had no idea where I was in terms of performance until it was to late and I’m left in this shitty, shitty situation where I cannot hope to pass anymore. It sucks, unbelievably, and so once again, we will see. Because I have nothing else left to do but wait for the outcome of this week.
        <p>`,
        preview: "This is probably the most important week in IM for me so far. In short, I am failing right now. At some point soon, I’ll try and ask for a chance to potentially redo assignment 1, or otherwise somehow recover a few marks. If that’s not an option, then it’s done. I’m not spending time or energy on a subject that I cannot possibly pass, and having done the maths, believe me when I say I cannot pass this class with my current average.",
        color: "flamingoback"
    },{
        id: 12,
        title: "Week 12",
        text: `<p>The Traveling While Trans reading was interesting because it highlights the systematic biases present within our institutions and the technology they use. This much is obvious, probably even to someone who doesn’t do this course, but I think it’s important to remember how many of the little assumptions we make while coding can have far reaching ramifications. Things like the assumption that all people who will be scanned in an airport are cisgender, or that people who use our website will have the same access to technology as us. I do also really appreciate the fact that the reading dives a bit more deeply into intersectionality. As many examples highlight, non-intersectional social justice can be just as harmful as the bigotry it opposes, especially when there are bad actors who are willing to find the loopholes within the proposed systems to deliberately oppress those who are especially vulnerable, such as transgender people or -very commonly throughout history- black women.<p>`,
        preview: "The Traveling While Trans reading was interesting because it highlights the systematic biases present within our institutions and the technology they use. This much is obvious, probably even to someone who doesn’t do this course, but I think it’s important to remember how many of the little assumptions we make while coding can have far reaching ramifications. Things like the assumption that all people who will be scanned in an airport are cisgender, or that people who use our website will have the same access to technology as us. I do also really appreciate the fact that the reading dives a bit more deeply into intersectionality. As many examples highlight, non-intersectional social justice can be just as harmful as the bigotry it opposes, especially when there are bad actors who are willing to find the loopholes within the proposed systems to deliberately oppress those who are especially vulnerable, such as transgender people or -very commonly throughout history- black women.",
        color: "greenback"
    },{
        id: 13,
        title: "Week 13",
        text: `<p>I will not lie, I’ve somewhat fallen off when it comes to the readings. There’s just been so much work as of late, and I’m barely keeping up as is. Add onto that being sick and celebrating my father’s birthday, and it’s got me reflecting on how one even keeps up with work at all. The solution, I suppose, is to adjust the workflow. I have always operated in a slow and steady manner, and while that usually works, I do not think that my regulation of work when two assignments overlap has been ideal. I generally focus on the closest deadline, rather than the largest workload, and while it usually works, occasionally it backfires and I find myself in a situation like I would have been in on the 5th of June had our due dates not changed, where I would have had three massive assignments due on a single day and no human way of completing them all on time. I suppose the logical conclusion is to divide up the time I spend working in accordance with workload, and move through things in that way, although that’d require more work in itself, at which point one must become careful to not make the act of dividing work cut into the work that actually needs to be done.</p><p>

        The one thing I did have a bit of time to research is the case of Plessy vs Ferguson, the so-called “Worst decision in Supreme Court History”. In short, a man named Homer Plessy was caught using a whites only rail cart in the late 1800s, and was punished despite only being partially black. His argument was that the already ratified 14th stated that all people were legally equal under the rule of law, however the court ultimately ruled that while all people are equal, that didn’t mean that there wasn’t still a distinction between black and white, and this case would go on to serve as legal precedent in many future cases that allowed the legal system to oppress marginalized communities even further. I bring this up because I said I’d research it in class, but also because I think it’s an interesting followup to my point last week, about how systems that are designed to protect can just as often oppress, and we need to really think about how we design our systems to make sure they aren’t used against others or ourselves. Because the worst part of this whole situation, is that the insidious precedent this case set wasn’t that black people couldn’t have things, they just couldn’t have the same things. And then all that the system had to do was just not provide the alternative, and suddenly it was possible for it to oppress black Americans in the exact same way as they did before the 14th and 15th amendment, just now with a legal and moral high ground.</p><p>
        <p>`,
        preview: "I will not lie, I’ve somewhat fallen off when it comes to the readings. There’s just been so much work as of late, and I’m barely keeping up as is. Add onto that being sick and celebrating my father’s birthday, and it’s got me reflecting on how one even keeps up with work at all. The solution, I suppose, is to adjust the workflow. I have always operated in a slow and steady manner, and while that usually works, I do not think that my regulation of work when two assignments overlap has been ideal. I generally focus on the closest deadline, rather than the largest workload, and while it usually works, occasionally it backfires and I find myself in a situation like I would have been in on the 5th of June had our due dates not changed, where I would have had three massive assignments due on a single day and no human way of completing them all on time. I suppose the logical conclusion is to divide up the time I spend working in accordance with workload, and move through things in that way, although that’d require more work in itself, at which point one must become careful to not make the act of dividing work cut into the work that actually needs to be done.",
        color: "coralback"
    },{
        id: 14,
        title: "Final Conclusion, Leg 2",
        text: `<p>So, the second leg of the assignment is done. It was awful.</p><p>

        The first major problem was my assignment 1 mark. I felt sick when I first saw it, and things didn’t get better from there. My assignment 2 was mediocre, and it took ages to get the situation with my assignment 1 mark sorted. Now that I have, I’m able to at least breathe a little, but I’m still stressed about this assignment. </p><p>
        
        Because having assignment 1 be a screw up was bad enough, but what it ultimately meant was that I wasted about a week not working on assignment 2 at all because thinking about IM as a subject was enough to send me spiraling. I’m a depressive person who’s prone to mood swings. Keeping my mental health in check is a constant battle. It was the right decision in the long run, of course, since it meant that at least I was only failing one subject and could recover from that, but it’s made this second part of building this website feel like a herculean task compared to the silly little exercise that was putting together the first half. </p><p>
        
        But enough excuses, what about the site? Well, there’s a lot I’m not happy with, but there are also some things I do like. For one, I really like the new blog and essay sections. They are a major step up from what came before, and they feel far more professional than the “baby’s first site” feeling stuff that came at first. Secondly, I feel as though I’ve improved my user interface a lot. The new top bar is cleaner and smoother, and the hamburger menu feels smooth and switches seamlessly, which I’m impressed by myself. I was able to implement some of the feedback from Andre, and just overall I think that everything about the site is just a little better than it was before.</p><p>

        I even upped my games with my dev process a bit. I've moved to Microsoft edge as my development browser, since it offers an easier to use set of in depth dev tools than Firefox, allowing me to prototype better and faster. It does come with the downside of me accidentally using a function that's not available on all browsers yet, creating a compatibility problem, but since there's not enough time to fix it, I think all I can hope for is that the problem is fixed soon and otherwise that the marker uses another browser to test this site. Besides, it's just a small part of the hamburger menu function, nothing site destroying. </p><p>
        
        That said, I’m also in a very negative mood today (breaking down into tears over your code does that) so I want to focus on what doesn’t work well. Firstly, the thing that made me break into tears. Some parts of my site don’t scale perfectly, and I ended up spending hours trying to fix them only to make things worse. Fortunately I was able to restore them (a powerful lesson in the importance of backing up), but it’s still frustrating that I wasted so much of my valuable last day on such dumb stuff. I’m also not overjoyed with the design section. If I had the time, I would have liked to expand it far more (in fact, that’s basically true of the whole site) but I just don’t have the time for anything that doesn’t get me marks. </p><p>
        
        All my fears about working on my old code also came true. There’s so much stuff that I just do better now and I wish I had known to do it when I started, but at least most of that is somewhat fixed now and I won’t have to worry about it again… at least until the next idiotic thing I did rears its ugly head.</p><p>
        
        So overall, the middle of the journey has been awful, but at the very least struggling like this hopefully means that the exam period will go a bit smoother because I’ve made all the screwups possible now and I can just work on the next assignment. I really hope so.
        <p>`,
        preview: "So, the second leg of the assignment is done. It was awful.",
        color: "blueback"
    }, 

]



const textArea = document.getElementById("texts");

var url = window.location.pathname;
var filename = url.substring(url.lastIndexOf('/')+1);

if(filename == "essays.html"){
    CreateTextEssay(essayTexts);
}else{
    CreateTextBlog(blogTexts);
}

    //Opening and closing functions

    var fullTextBox = document.getElementById("fullTextBox");
    var fullText = document.getElementById("fullText");

    function OpenFull(ID){
        fullTextBox.style.display = "flex";
        if(filename == "essays.html"){
            fullText.innerHTML = essayTexts.at(ID).text;
        }else{
            fullText.innerHTML = blogTexts.at(ID).text;
        }
        
    }

    function CloseFull(){
        fullTextBox.style.display = "none";
    }

    //Essay creation script

function CreateTextEssay(essayItems){
    var CreateTextEssay = essayItems.map(function (essayItem){
      return `<article class="essay-container">

      <div class="essay-box">
          <div class="essay-img">
              <img src="${essayItem.thumbnail}" alt="${essayItem.thumbnailAlt}">
          </div>
      </div>
      <div class="essay-text">
          <span>${essayItem.date}/ ${essayItem.subject}</span>
          <a onclick="OpenFull(${essayItem.id})" class = "essay-title">${essayItem.title}</a>
          <p>${essayItem.previewparagraph} </p>
          <h3 onclick="OpenFull(${essayItem.id})">Read More </h3>
      </div>

  </article>`;
    }).join("");
  
    textArea.innerHTML = CreateTextEssay;
  }

  function CreateTextBlog(blogItems){
    var CreateTextBlog = blogItems.map(function (blogItem){
      return `<article class="grid-item ${blogItem.color}">
      <h2 class="post-heading">${blogItem.title}</h2>
      <div class="post-text">
          <p>${blogItem.preview}</p>
          <h3 onclick="OpenFull(${blogItem.id})">Read More</h3>
      </div>
    </article>`;
    }).join("");
  
    textArea.innerHTML = CreateTextBlog;
  }




